name: Pico Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ARM Toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi cmake ninja-build

      - name: Clone Pico SDK
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init

      - name: Configure Build
        run: |
          mkdir build
          cd build
          cmake .. -DPICO_SDK_PATH=../pico-sdk

      - name: Build Project
        run: |
          cd build
          make

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: pico-firmware
          path: build/*.uf2